version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/toxicity_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toxicity_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
