version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "python -c 'from app.database import Base, engine; Base.metadata.drop_all(bind=engine); Base.metadata.create_all(bind=engine)' && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    
    environment:
      - DATABASE_URL=postgresql://user:password@db/toxicity_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toxicity_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
